# Generated by Django 4.2.1 on 2023-05-21 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название региона')),
                ('url', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(null=True, verbose_name='Отображать вакансию')),
                ('name', models.CharField(max_length=150, verbose_name='Название вакансии')),
                ('city', models.CharField(max_length=150, verbose_name='Город')),
                ('pay', models.CharField(max_length=150, verbose_name='Введите зарплату')),
                ('snippet', models.CharField(max_length=600, verbose_name='Сниппет карточки')),
                ('url', models.SlugField(max_length=150, unique=True)),
                ('work_experience', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Опыт работы')),
                ('Responsibilities_1', models.CharField(blank=True, default='-', max_length=150, null=True, verbose_name='Введите обязанности')),
                ('Responsibilities_2', models.CharField(blank=True, default='-', max_length=150, null=True, verbose_name='Введите обязанности')),
                ('Responsibilities_3', models.CharField(blank=True, default='-', max_length=150, null=True, verbose_name='Введите обязанности')),
                ('Responsibilities_4', models.CharField(blank=True, default='-', max_length=150, null=True, verbose_name='Введите обязанности')),
                ('Responsibilities_5', models.CharField(blank=True, default='-', max_length=150, null=True, verbose_name='Введите обязанности')),
                ('Responsibilities_6', models.CharField(blank=True, default='-', max_length=150, null=True, verbose_name='Введите обязанности')),
                ('Responsibilities_7', models.CharField(blank=True, default='-', max_length=150, null=True, verbose_name='Введите обязанности')),
                ('Responsibilities_8', models.CharField(blank=True, default='-', max_length=150, null=True, verbose_name='Введите обязанности')),
                ('Responsibilities_9', models.CharField(blank=True, default='-', max_length=150, null=True, verbose_name='Введите обязанности')),
                ('Responsibilities_10', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Введите обязанности')),
                ('Requirements_1', models.CharField(blank=True, default='-', max_length=150, verbose_name='Введите требования')),
                ('Requirements_2', models.CharField(blank=True, default='-', max_length=150, verbose_name='Введите требования')),
                ('Requirements_3', models.CharField(blank=True, default='-', max_length=150, verbose_name='Введите требования')),
                ('Requirements_4', models.CharField(blank=True, default='-', max_length=150, verbose_name='Введите требования')),
                ('Requirements_5', models.CharField(blank=True, default='-', max_length=150, verbose_name='Введите требования')),
                ('Requirements_6', models.CharField(blank=True, default='-', max_length=150, verbose_name='Введите требования')),
                ('Requirements_7', models.CharField(blank=True, default='-', max_length=150, verbose_name='Введите требования')),
                ('Requirements_8', models.CharField(blank=True, default='-', max_length=150, verbose_name='Введите требования')),
                ('Requirements_9', models.CharField(blank=True, default='-', max_length=150, verbose_name='Введите требования')),
                ('Requirements_10', models.CharField(blank=True, default='-', max_length=150, verbose_name='Введите требования')),
                ('Terms_1', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Введите условия')),
                ('Terms_2', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Введите условия')),
                ('Terms_3', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Введите условия')),
                ('Terms_4', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Введите условия')),
                ('Terms_5', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Введите условия')),
                ('Terms_6', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Введите условия')),
                ('Terms_7', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Введите условия')),
                ('Terms_8', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Введите условия')),
                ('Terms_9', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Введите условия')),
                ('Terms_10', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Введите условия')),
                ('Core_skills_1', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Введите ключевые навыки')),
                ('Core_skills_2', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Введите ключевые навыки')),
                ('Core_skills_3', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Введите ключевые навыки')),
                ('Core_skills_4', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Введите ключевые навыки')),
                ('Core_skills_5', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Введите ключевые навыки')),
                ('Core_skills_6', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Введите ключевые навыки')),
                ('Core_skills_7', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Введите ключевые навыки')),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.category', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='JobResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('job_application', models.CharField(max_length=1000, verbose_name='Расскажите о себе')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
            },
        ),
    ]
