# Generated by Django 4.2.1 on 2023-05-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_remove_vacancy_core_skills_6_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobresponse',
            name='staus',
            field=models.CharField(choices=[('N', 'Новый отклик'), ('I', 'В процессе рассмотрения'), ('C', 'Закрытый отклик')], default='N', max_length=1, verbose_name='Статус рассмотрения'),
        ),
    ]
