# Generated by Django 4.2.1 on 2023-05-21 06:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_rename_staus_jobresponse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobresponse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
