# Generated by Django 4.2.1 on 2023-05-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_jobresponse_uuid_alter_jobresponse_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobresponse',
            name='uuid',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
