# Generated by Django 4.2.1 on 2023-05-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_jobresponse_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobresponse',
            name='files',
            field=models.FileField(default='', upload_to='Uploaded Files/', verbose_name=''),
        ),
    ]
