# Generated by Django 4.2.1 on 2023-05-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_remove_jobresponse_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobresponse',
            name='job_application',
            field=models.CharField(default='', max_length=10),
        ),
    ]
