# Generated by Django 4.2.1 on 2023-05-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_alter_jobresponse_job_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='url',
        ),
        migrations.AlterField(
            model_name='jobresponse',
            name='job_application',
            field=models.FileField(default='', upload_to='Uploaded Files/'),
        ),
    ]
