# Generated by Django 4.2.1 on 2023-05-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_remove_vacancy_url_alter_jobresponse_job_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='work_busy',
            field=models.CharField(default='', max_length=150, verbose_name='Тип занятости'),
        ),
    ]
