# Generated by Django 4.2.1 on 2023-05-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_alter_vacancy_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='Core_skills_1',
            field=models.TextField(blank=True, default='', max_length=150, null=True, verbose_name='Введите ключевые навыки'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Core_skills_2',
            field=models.TextField(blank=True, default='', max_length=150, null=True, verbose_name='Введите ключевые навыки'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Core_skills_3',
            field=models.TextField(blank=True, default='', max_length=150, null=True, verbose_name='Введите ключевые навыки'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Core_skills_4',
            field=models.TextField(blank=True, default='', max_length=150, null=True, verbose_name='Введите ключевые навыки'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Core_skills_5',
            field=models.TextField(blank=True, default='', max_length=150, null=True, verbose_name='Введите ключевые навыки'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Requirements_1',
            field=models.TextField(blank=True, default='-', max_length=150, verbose_name='Введите требования'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Requirements_2',
            field=models.TextField(blank=True, default='-', max_length=150, verbose_name='Введите требования'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Requirements_3',
            field=models.TextField(blank=True, default='-', max_length=150, verbose_name='Введите требования'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Requirements_4',
            field=models.TextField(blank=True, default='-', max_length=150, verbose_name='Введите требования'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Requirements_5',
            field=models.TextField(blank=True, default='-', max_length=150, verbose_name='Введите требования'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Responsibilities_1',
            field=models.TextField(blank=True, default='-', max_length=150, null=True, verbose_name='Введите обязанности'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Responsibilities_2',
            field=models.TextField(blank=True, default='-', max_length=150, null=True, verbose_name='Введите обязанности'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Responsibilities_3',
            field=models.TextField(blank=True, default='-', max_length=150, null=True, verbose_name='Введите обязанности'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Responsibilities_4',
            field=models.TextField(blank=True, default='-', max_length=150, null=True, verbose_name='Введите обязанности'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Responsibilities_5',
            field=models.TextField(blank=True, default='-', max_length=150, null=True, verbose_name='Введите обязанности'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Terms_1',
            field=models.TextField(blank=True, default='', max_length=150, null=True, verbose_name='Введите условия'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Terms_2',
            field=models.TextField(blank=True, default='', max_length=150, null=True, verbose_name='Введите условия'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Terms_3',
            field=models.TextField(blank=True, default='', max_length=150, null=True, verbose_name='Введите условия'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Terms_4',
            field=models.TextField(blank=True, default='', max_length=150, null=True, verbose_name='Введите условия'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Terms_5',
            field=models.TextField(blank=True, default='', max_length=150, null=True, verbose_name='Введите условия'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='snippet',
            field=models.TextField(max_length=10000, verbose_name='Сниппет карточки'),
        ),
    ]
