# Generated by Django 4.2.1 on 2023-05-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_alter_vacancy_core_skills_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobresponse',
            name='surname',
            field=models.CharField(default='', max_length=50, verbose_name='Фамилия'),
        ),
    ]
