# Generated by Django 4.2.1 on 2023-05-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_jobresponse_surname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobresponse',
            options={'verbose_name': 'Тикет', 'verbose_name_plural': 'Тикеты'},
        ),
        migrations.AlterField(
            model_name='jobresponse',
            name='number',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
        ),
    ]
