# Generated by Django 4.2.1 on 2023-06-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_alter_jobresponse_options_alter_jobresponse_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='Terms_4',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='Terms_5',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='snippet',
            field=models.TextField(max_length=300, verbose_name='Сниппет карточки'),
        ),
    ]
